### ISSUE TITLE
can't run app on colab,got error.

### ISSUE THREAD

**Issue by eleven-monkey** [qunash/stable-diffusion-2-gui#12]
when I click play button of run the app section,got an error:

OSError: [Errno 36] File name too long: '.main-div div{display:inline-flex;align-items:center;gap:.8rem;font-size:1.75rem}.main-div div h1{font-weight:900;margin-bottom:7px}.main-div p{margin-bottom:10px;font-size:94%}a{text-decoration:underline}.tabs{margin-top:0;margin-bottom:0}#gallery{min-height:20rem}\n'

**Comment by sin-ivan** [comment]
I have the same error, but it worked some time ago.

**Comment by akaarrow** [comment]
The problem comes from the following line located in the "Run The App" cell:

```
css = """.main-div div{display:inline-flex;align-items:center;gap:.8rem;font-size:1.75rem}.main-div div h1{font-weight:900;margin-bottom:7px}.main-div p{margin-bottom:10px;font-size:94%}a{text-decoration:underline}.tabs{margin-top:0;margin-bottom:0}#gallery{min-height:20rem}
"""
```

Just remove a little part of it, e.g. ;

```
css = """.main-div div{display:inline-flex;align-items:center;gap:.8rem;font-size:1.75rem}.main-div div h1{font-weight:900;
"""
```

Hope this work for you too :)
@sin-ivan @eleven-monkey

**Comment by qunash** [comment]
Hi, thanks for the report!
This has been fixed now.
