### ISSUE TITLE
Colab not working

### ISSUE THREAD

**Issue by ChaseFlorom** [qunash/stable-diffusion-2-gui#15]
Hey, as I run the colab cells I'm getting this error:

`NameError                                 Traceback (most recent call last)
[<ipython-input-2-c92a6aca1dc2>](https://localhost:8080/#) in <module>
    413 
    414               gallery = gr.Gallery(label="Generated images", show_label=False).style(grid=[2], height="auto")
--> 415           state_info = gr.Textbox(label="State", show_label=False, max_lines=2, interactive=false).style(container=False)
    416           error_output = gr.Markdown(visible=False)
    417`

**Comment by qunash** [comment]
Fixed, thank you for the report
