### ISSUE TITLE
I was getting only black images. 

### ISSUE THREAD

**Issue by amrrs** [qunash/stable-diffusion-2-gui#3]
Only black images for whatever prompt 

This could be a potential solution

https://www.reddit.com/r/StableDiffusion/comments/zf21db/comment/iz9sh0i/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by qunash** [comment]
Yeah, sorry about that. It's fixed now

**Comment by amrrs** [comment]
I used your Stable Diffusion GUI for my latest tutorial https://www.youtube.com/watch?v=NS2mzmH-lpk

**Comment by qunash** [comment]
Great
