### ISSUE TITLE
Error when wanting to upscale

### ISSUE THREAD

**Issue by enzyme69** [qunash/stable-diffusion-2-gui#4]
I kept getting this:
upscale() takes 7 positional arguments but 8 were given

I think 4x upscale should just be a button. Not drag and drop and needing prompting. But I am curious how it could actually work, if it can add details while upscaling.

**Comment by spl3g** [comment]
Now there is another error when you try to upscale:
'NoneType' object is not callable

**Comment by qunash** [comment]
@spl3g fixed now, thanks
