### ISSUE TITLE
Sampling methods

### ISSUE THREAD

**Issue by joanroig** [qunash/stable-diffusion-2-gui#5]
Hello, I wanted to ask which is the sampling method used for this tool, as I was unable to find any reference in the code

**Comment by qunash** [comment]
Hello, sampler used is DPM-Solver - https://github.com/LuChengTHU/dpm-solver, as referenced in `readme.md`

**Comment by joanroig** [comment]
I see, many thanks for the fast answer! Very nice tool by the way, thanks for it.
