### ISSUE TITLE
Colab - Cuda OOM 

### ISSUE THREAD

**Issue by amrrs** [qunash/stable-diffusion-2-gui#6]
After trying Depth-to-Image model a 4 or 5 times, I got this error. 

```
CUDA out of memory. Tried to allocate 6.78 GiB (GPU 0; 14.76 GiB total capacity; 6.31 GiB already allocated; 5.71 GiB free; 7.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I'm not sure if something wrong happens with the D2I model. Just letting you know!

**Comment by amrrs** [comment]
This was on a Free Colab

**Comment by qunash** [comment]
Thanks for the info, I'll look into that

**Comment by amrrs** [comment]
I'll close it. It looks like it has to do with image size. Whenever the image size crosses 1000px, this happens.
