### ISSUE TITLE
img2img error

### ISSUE THREAD

**Issue by bebop47** [qunash/stable-diffusion-2-gui#7]
I cant get img2img to work. I am getting this error:

Error
Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_img2img.StableDiffusionImg2ImgPipeline'> expected {'unet', 'text_encoder', 'scheduler', 'feature_extractor', 'vae', 'safety_checker', 'tokenizer'}, but only {'unet', 'text_encoder', 'scheduler', 'vae', 'tokenizer'} were passed.

**Comment by qunash** [comment]
Fixed it, thanks for the report.
